keys:
  - &barrucadu 'age1sdnp5uxhdtujc78penv2gntnenzcfju7est4hslz6eqgfk26u9nskkk634'

creation_rules:
  - path_regex: hosts/carcosa/secrets(/[^/]+)?\.yaml$
    key_groups:
      - age:
          - *barrucadu
          - 'age1ty4vs59695vuavnvgdftguyq2aau29nv75y4tqrr6ag8z26vfc5sc5rc4n'

  - path_regex: hosts/nyarlathotep/secrets(/[^/]+)?\.yaml$
    key_groups:
      - age:
          - *barrucadu
          - 'age1700sgwfejx38fh66k6sajxe507w9x6ptcxfh4dmyffflml75w4fqmteyfy'

  - path_regex: hosts/yuggoth/secrets(/[^/]+)?\.yaml$
    key_groups:
      - age:
          - *barrucadu
          - 'age1xj0vderjss6wvyuu5uw5gag6lhxzfh6qwfrewgpff5ttpfa03azsxc8600'
