{
  imports = [
    ./common.nix
    ./host/configuration.nix
    ./host/hardware.nix
    ./modules/backup-scripts.nix
    ./modules/erase-your-darlings.nix
    ./modules/firewall.nix
    ./modules/monitoring-scripts.nix
    ./modules/zfs-automation.nix
    ./services/bookdb.nix
    ./services/bookmarks.nix
    ./services/commento.nix
    ./services/concourse.nix
    ./services/finder.nix
    ./services/gitea.nix
    ./services/minecraft.nix
    ./services/pihole.nix
    ./services/pleroma.nix
    ./services/umami.nix
  ];
}
