# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = 
   [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
   ];

  boot.initrd.availableKernelModules = [ "ata_piix" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ef78e4d7-771c-44be-8f32-e36daa953bb7";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3dcc2874-a0e4-4bbb-b2e2-f26b4ef298fd"; }
    ];

  nix.maxJobs = 2;
}
