# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = 
   [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
   ];

  boot.initrd.availableKernelModules = [ "ata_piix" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ef78e4d7-771c-44be-8f32-e36daa953bb7";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4c266717-5fa9-4f82-9546-fac7dfc3da76";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fd1671e4-fb76-4493-9e9a-ca42c9520430"; }
    ];

  nix.maxJobs = 2;
}
