{
 "title": "DNS Resolver",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(dns_requests_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dns_requests_total{job=\"$Job\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dns_requests_total{job=\"$Job\"}[$__interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(dns_responses_total{job=\"$Job\"}) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(dns_responses_total{job=\"$Job\"}[$__interval])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Questions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(dns_questions_total{job=\"$Job\"}) by(qclass, qtype)",
     "legendFormat": "{{qclass}} {{qtype}}"
    }
   ]
  },
  {
   "title": "Answered Locally",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "dns_resolver_authoritative_hit_total{job=\"$Job\"}",
     "legendFormat": "Authoritatively"
    },
    {
     "expr": "dns_resolver_blocked_total{job=\"$Job\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "dns_resolver_cache_hit_total{job=\"$Job\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "dns_resolver_override_hit_total{job=\"$Job\"}",
     "legendFormat": "Overridden"
    }
   ]
  },
  {
   "title": "Upstream Nameserver Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "dns_resolver_nameserver_hit_total{job=\"$Job\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "dns_resolver_nameserver_miss_total{job=\"$Job\"}",
     "legendFormat": "Misses"
    },
    {
     "expr": "dns_resolver_nameserver_hit_total{job=\"$Job\"} / (dns_resolver_nameserver_hit_total{job=\"$Job\"} + dns_resolver_nameserver_miss_total{job=\"$Job\"})",
     "legendFormat": "Ratio"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Effectiveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "dns_resolver_cache_hit_total{job=\"$Job\"}",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "dns_resolver_cache_miss_total{job=\"$Job\"}",
     "legendFormat": "Cache Misses"
    },
    {
     "expr": "dns_resolver_cache_hit_total{job=\"$Job\"} / (dns_resolver_cache_hit_total{job=\"$Job\"} + dns_resolver_cache_miss_total{job=\"$Job\"})",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Activity per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(dns_resolver_cache_hit_total{job=\"$Job\"}[$__interval])",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "rate(dns_resolver_cache_miss_total{job=\"$Job\"}[$__interval])",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "cache_size{job=\"$Job\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Eviction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "cache_expired_total{job=\"$Job\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "cache_pruned_total{job=\"$Job\"}",
     "legendFormat": "Pruned"
    }
   ]
  },
  {
   "title": "Evictions per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cache_expired_total{job=\"$Job\"}[$__interval])",
     "legendFormat": "Expiration"
    },
    {
     "expr": "rate(cache_pruned_total{job=\"$Job\"}[$__interval])",
     "legendFormat": "Pruning"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$Job\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$Job\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$Job\"}[$__interval])",
     "legendFormat": "Resident"
    }
   ]
  }
 ]
}