{
 "title": "Personal Finances",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Net Worth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"assets[£]\" +\"liabilities[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Savings Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"assets[£]\"-\"expenses[£]\" )/\"assets[£]\" FROM \"period\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Short Runway",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"assets:cash[£]\") + last(\"assets:investments:nsi:premium_bonds:emergency[£]\")) / ((last(\"expenses[£]\") - first(\"expenses[£]\") - last(\"expenses:gross[£]\") + first(\"expenses:gross[£]\")) / count(\"expenses[£]\")) FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Long Runway",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"assets[£]\")  / ((last(\"expenses[£]\") - first(\"expenses[£]\") - last(\"expenses:gross[£]\") + first(\"expenses:gross[£]\")) / count(\"expenses[£]\")) FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "House Deposit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "market",
     "query": "SELECT \"assets:investments:ajbell[£]\" + \"assets:investments:nsi:premium_bonds:house[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "assets:cash:nationwide:flexdirect:pending:ajbell[£]"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Student Loan",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"liabilities:loan:slc[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "count",
     "query": "SELECT \"cleared\" + \"pending\" + \"uncleared\" FROM \"count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cleared" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Asset Allocation",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "format": "currencyGBP",
   "valueName": "current",
   "targets": [
    {
     "alias": "Cash",
     "measurement": "market",
     "query": "SELECT \"assets:cash[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets:cash[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Investments",
     "measurement": "market",
     "query": "SELECT \"assets:investments[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets:investments[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Receivable",
     "measurement": "market",
     "query": "SELECT \"assets:receivable[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets:receivable[£]" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cash",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "format": "currencyGBP",
   "valueName": "current",
   "targets": [
    {
     "alias": "Nationwide",
     "measurement": "market",
     "query": "SELECT \"assets:cash:nationwide[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets:cash:nationwide[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Starling",
     "measurement": "market",
     "query": "SELECT \"assets:cash:starling[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets:cash:starling[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Petty Cash",
     "measurement": "market",
     "query": "SELECT \"assets:cash:petty[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets:cash:petty[£]" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Investments",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "format": "currencyGBP",
   "valueName": "current",
   "targets": [
    {
     "alias": "S&S ISA",
     "measurement": "market",
     "query": "SELECT \"assets:investments:cavendish[£]\" + \"assets:investments:fidelity[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "assets:investments:cavendish[£]"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "S&S LISA",
     "measurement": "market",
     "query": "SELECT \"assets:investments:ajbell[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "assets:investments:fundingcircle[£]"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Premium Bonds",
     "measurement": "market",
     "query": "SELECT \"assets:investments:nsi:premium_bonds[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "assets:investments:nsi:premium_bonds[£]"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cleared",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "count",
     "query": "SELECT * FROM \"count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cleared" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uncleared",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "count",
     "query": "SELECT * FROM \"count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "uncleared" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bookkeeping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "count",
     "query": "SELECT * FROM \"count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bookkeeping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "count",
     "query": "SELECT \"pending\" / (\"pending\" + \"cleared\" + \"uncleared\") FROM \"count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" },
       { "params": [ "/cleared" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Worth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "alias": "Total Assets",
     "measurement": "market",
     "query": "SELECT \"assets[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Total Liabilities",
     "measurement": "market",
     "query": "SELECT \"liabilities[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Delta",
     "measurement": "market",
     "query": "SELECT \"assets[£]\" +\"liabilities[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Credit Card",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "alias": "Put Aside",
     "measurement": "market",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:pending:amex[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Liability",
     "measurement": "market",
     "query": "SELECT \"liabilities:creditcard:amex[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Delta",
     "measurement": "market",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:pending:amex[£]\" +\"liabilities:creditcard:amex[£]\" FROM \"market\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cash Flow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "alias": "Income (net)",
     "measurement": "market",
     "query": "SELECT \"assets[£]\"   FROM \"period\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Expenses",
     "measurement": "market",
     "query": "SELECT -\"expenses[£]\"   FROM \"period\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Delta",
     "measurement": "market",
     "query": "SELECT \"assets[£]\"-\"expenses[£]\"  FROM \"period\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Savings Rate",
     "measurement": "market",
     "query": "SELECT (\"assets[£]\"-\"expenses[£]\" )/\"assets[£]\" FROM \"period\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "assets[£]" ], "type": "field" }
      ],
      [
       { "params": [ "liabilities[£]" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Emergency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:investments:nsi:premium_bonds:emergency[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Float",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:float[£]\"  + \"assets:cash:starling:float[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gift",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:saved:gift[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Graze",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:saved:graze[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:saved:health[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Household",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:saved:household[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Move",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:investments:nsi:premium_bonds:move[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Patreon",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:starling:patreon[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Phone",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:saved:phone[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protonmail",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:starling:protonmail[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:saved:rent[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Roll20",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:starling:roll20[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Travel",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:saved:travel[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Utilities",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:nationwide:flexdirect:saved:utilities[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Web",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "normal",
     "query": "SELECT \"assets:cash:starling:web[£]\" FROM \"normal\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Market Prices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bitcoin Unit Value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "currencyGBP" }
     ],
     "targets": [
      {
       "alias": "BTC",
       "measurement": "market",
       "query": "SELECT \"BTC[£]\" FROM \"commodities\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "BTC[£]" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ethereum Unit Value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "currencyGBP" }
     ],
     "targets": [
      {
       "alias": "ETH",
       "measurement": "market",
       "query": "SELECT \"ETH[£]\" FROM \"commodities\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "BTC[£]" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Litecoin Unit Value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "currencyGBP" }
     ],
     "targets": [
      {
       "alias": "LTC",
       "measurement": "market",
       "query": "SELECT \"LTC[£]\" FROM \"commodities\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "BTC[£]" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Euro Unit Value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "currencyGBP" }
     ],
     "targets": [
      {
       "alias": "EUR",
       "measurement": "market",
       "query": "SELECT \"EUR[£]\" FROM \"commodities\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "BTC[£]" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Japanese Yen Unit Value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "currencyGBP" }
     ],
     "targets": [
      {
       "alias": "JPY",
       "measurement": "market",
       "query": "SELECT \"JPY[£]\" FROM \"commodities\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "BTC[£]" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "US Dollar Unit Value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "currencyGBP" }
     ],
     "targets": [
      {
       "alias": "USD",
       "measurement": "market",
       "query": "SELECT \"USD[£]\" FROM \"commodities\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "BTC[£]" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Vanguard LifeStrategy 100% (Acc) Fund Unit Value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "currencyGBP" }
     ],
     "targets": [
      {
       "alias": "VANEA",
       "measurement": "market",
       "query": "SELECT \"VANEA[£]\" FROM \"commodities\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "BTC[£]" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}