{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{job=\"nyarlathotep-node\"} - node_boot_time_seconds{job=\"nyarlathotep-node\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"nyarlathotep-node\",mode!=\"idle\"}[1m])) / count(count by (cpu) (node_cpu_seconds_total{job=\"nyarlathotep-node\"}))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{job=\"nyarlathotep-node\"} / node_memory_MemTotal_bytes{job=\"nyarlathotep-node\"})"
    }
   ]
  },
  {
   "title": "Pi Hole",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_status{job=\"pihole-pihole\"}"
    }
   ]
  },
  {
   "title": "Total queries today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_dns_queries_all_types{job=\"pihole-pihole\"}"
    }
   ]
  },
  {
   "title": "Unique domains today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_unique_domains{job=\"pihole-pihole\"}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "scalar(node_time_seconds{job=\"nyarlathotep-node\"}) - docker_container_start_time_seconds{job=\"nyarlathotep-docker\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (cpu) (node_cpu_seconds_total{job=\"nyarlathotep-node\"}))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nyarlathotep-node\"}"
    }
   ]
  },
  {
   "title": "Domains on blocklist",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{job=\"pihole-pihole\"}"
    }
   ]
  },
  {
   "title": "Queries blocked today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_ads_blocked_today{job=\"pihole-pihole\"}"
    }
   ]
  },
  {
   "title": "Queries blocked today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{job=\"pihole-pihole\"}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{job=\"nyarlathotep-node\",mountpoint=~\"/|/boot|/mnt/nas\"} / node_filesystem_size_bytes{job=\"nyarlathotep-node\",mountpoint=~\"/|/boot|/mnt/nas\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "avg(node_load5{job=\"nyarlathotep-node\"}) / count(count by (cpu) (node_cpu_seconds_total{job=\"nyarlathotep-node\"}))"
    }
   ]
  },
  {
   "title": "Load (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "avg(node_load15{job=\"nyarlathotep-node\"}) / count(count by (cpu) (node_cpu_seconds_total{job=\"nyarlathotep-node\"}))"
    }
   ]
  },
  {
   "title": "Queries answered by",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(pihole_forward_destinations{job=\"pihole-pihole\"}, \"target\", \"$1\", \"destination\", \"(.*)\\\\|(.*)\")) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Speedtest Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expr": "scalar(speedtest_download)" }
   ]
  },
  {
   "title": "Speedtest Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "targets": [
    { "expr": "scalar(speedtest_upload)" }
   ]
  },
  {
   "title": "Speedtest Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "scalar(speedtest_ping_latency)" }
   ]
  },
  {
   "title": "Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(node_network_transmit_bytes_total{device=~\"eth0|enp4s0\"}[1m]), \"host\", \"$1\", \"job\", \"(.*)-node\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(node_network_receive_bytes_total{device=~\"eth0|enp4s0\"}[1m]), \"host\", \"$1\", \"job\", \"(.*)-node\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Top permitted domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "pihole_top_queries{job=\"pihole-pihole\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top blocked domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "pihole_top_ads{job=\"pihole-pihole\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top query sources",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "pihole_top_sources{job=\"pihole-pihole\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 39 }, "content": "# Disk usage:" },
  {
   "title": "nyarlathotep /",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 39 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nyarlathotep-node\",mountpoint=\"/\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"nyarlathotep-node\",mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"nyarlathotep-node\",mountpoint=\"/\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "nyarlathotep /boot",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 39 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nyarlathotep-node\",mountpoint=\"/boot\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"nyarlathotep-node\",mountpoint=\"/boot\"} - node_filesystem_avail_bytes{job=\"nyarlathotep-node\",mountpoint=\"/boot\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "nyarlathotep /mnt/nas",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 39 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nyarlathotep-node\",mountpoint=\"/mnt/nas\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"nyarlathotep-node\",mountpoint=\"/mnt/nas\"} - node_filesystem_avail_bytes{job=\"nyarlathotep-node\",mountpoint=\"/mnt/nas\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "pihole /",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 39 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"pihole-node\",mountpoint=\"/\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"pihole-node\",mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"pihole-node\",mountpoint=\"/\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "pihole /boot",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 39 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"pihole-node\",mountpoint=\"/boot\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"pihole-node\",mountpoint=\"/boot\"} - node_filesystem_avail_bytes{job=\"pihole-node\",mountpoint=\"/boot\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "nyarlathotep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"nyarlathotep-node\",mode!=\"idle\"}[1m])) by (cpu)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "pihole",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"pihole-node\",mode!=\"idle\"}[1m])) by (cpu)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 46 }, "content": "# CPU usage:" },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 53 }, "content": "# RAM usage:" },
  {
   "title": "nyarlathotep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{job=\"nyarlathotep-node\"} / node_memory_MemTotal_bytes{job=\"nyarlathotep-node\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"nyarlathotep-node\"} / node_memory_MemTotal_bytes{job=\"nyarlathotep-node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"nyarlathotep-node\"} - node_memory_MemFree_bytes{job=\"nyarlathotep-node\"} - node_memory_Buffers_bytes{job=\"nyarlathotep-node\"} - node_memory_Cached_bytes{job=\"nyarlathotep-node\"}) / node_memory_MemTotal_bytes{job=\"nyarlathotep-node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"nyarlathotep-node\"} / node_memory_MemTotal_bytes{job=\"nyarlathotep-node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "pihole",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{job=\"pihole-node\"} / node_memory_MemTotal_bytes{job=\"pihole-node\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"pihole-node\"} / node_memory_MemTotal_bytes{job=\"pihole-node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"pihole-node\"} - node_memory_MemFree_bytes{job=\"pihole-node\"} - node_memory_Buffers_bytes{job=\"pihole-node\"} - node_memory_Cached_bytes{job=\"pihole-node\"}) / node_memory_MemTotal_bytes{job=\"pihole-node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"pihole-node\"} / node_memory_MemTotal_bytes{job=\"pihole-node\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}