{
 "title": "Quantified Self",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Where does the time go?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg. Daily Sleep Deficit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timedot",
     "query": "SELECT 8-\"value\"  FROM \"timedot.hours.top.Sleep\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work" }
     ]
    }
   ]
  },
  {
   "title": "Avg. Daily Work Deficit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timedot",
     "query": "SELECT 8-\"value\"  FROM \"timedot.hours.top.Work\" WHERE $timeFilter AND \"is_work_day\" = 'yes'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work" }
     ]
    }
   ]
  },
  {
   "title": "Avg. Daily Missing Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timedot",
     "query": "SELECT 24-\"value\" FROM \"timedot.hours.__\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work" }
     ]
    }
   ]
  },
  {
   "title": "Total Sleep Deficit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timedot",
     "query": "SELECT 8-\"value\"  FROM \"timedot.hours.top.Sleep\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work" }
     ]
    }
   ]
  },
  {
   "title": "Total Work Deficit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timedot",
     "query": "SELECT 8-\"value\"  FROM \"timedot.hours.top.Work\" WHERE $timeFilter AND \"is_work_day\" = 'yes'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work" }
     ]
    }
   ]
  },
  {
   "title": "Total Missing Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timedot",
     "query": "SELECT 24-\"value\"  FROM \"timedot.hours.__\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work" }
     ]
    }
   ]
  },
  {
   "title": "Days Since Last Day Off",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timedot",
     "query": "SELECT \"value\" FROM \"timedot.streaks.top.Work\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work" }
     ]
    }
   ]
  },
  {
   "title": "% Leisure Hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"top.Leisure\" / (\"__\" - \"top.Sleep\") FROM \"timedot.hours.as_fields\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "$3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "timedot",
     "query": "SELECT \"value\" FROM /timedot.hours.top..*/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "leisure" }
     ]
    },
    {
     "alias": "Deficit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 24-\"value\"  FROM \"timedot.hours.__\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leisure Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "$5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "timedot",
     "query": "SELECT \"value\" FROM /timedot.hours.tag.leisure.is..*/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work:lunch" }
     ]
    }
   ]
  },
  {
   "title": "Work Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "$5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "timedot",
     "query": "SELECT \"value\" FROM /timedot.hours.tag.work.is..*/ WHERE $timeFilter AND \"is_work_day\" = 'yes'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work:admin" }
     ]
    },
    {
     "alias": "Deficit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timedot.hours.top.Work",
     "query": "SELECT 8-\"value\" FROM \"timedot.hours.top.Work\" WHERE $timeFilter AND \"is_work_day\" = 'yes'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "An Average Work Day",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "timedot",
     "query": "SELECT \"value\" FROM /timedot.hours.tag.work.cat1..*/ WHERE $timeFilter AND \"is_work_day\" = 'yes'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work:admin" }
     ]
    }
   ]
  },
  {
   "title": "An Average Work Day",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "timedot",
     "query": "SELECT \"value\" FROM /timedot.hours.tag.work.cat2..*/ WHERE $timeFilter AND \"is_work_day\" = 'yes'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "work:__active" }
     ]
    }
   ]
  },
  { "title": "Getting Things Done", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "To Do",
     "measurement": "trello",
     "query": "SELECT \"value\" FROM \"trello.list.TODO.count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "TODO__count" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Doing",
     "measurement": "trello",
     "query": "SELECT \"value\" FROM \"trello.list.IN_PROGRESS.count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "TODO__count" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Done",
     "measurement": "trello",
     "query": "SELECT \"value\" FROM \"trello.list.DONE.count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "TODO__count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "To Do",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$4",
     "measurement": "trello",
     "query": "SELECT \"value\" FROM /trello.list.TODO.count..*/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "DONE__count__/tea/ RPG Group" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Done",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$4",
     "measurement": "trello",
     "query": "SELECT \"value\" FROM /trello.list.DONE.count..*/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "DONE__count__/tea/ RPG Group" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "How fit am I?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Weight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    {
     "alias": "Weight",
     "measurement": "weight",
     "query": "SELECT \"value\" FROM \"weight\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overweight Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1.72 * 1.72 * 25 + \"value\"*0 FROM \"weight\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BMI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "BMI",
     "measurement": "weight",
     "query": "SELECT \"value\" / (1.72 * 1.72) FROM \"weight\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Underweight Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1.72 * 1.72 * 18.5 + \"value\"*0 FROM \"weight\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}