{
 "title": "Smart Home",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Living Room",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awair_score{sensor=\"living-room\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "awair_temp", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "awair_humid", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Carbon Dioxide",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "awair_co2", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Volatile Organic Compounds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    { "expr": "awair_voc", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "awair_pm25", "legendFormat": "{{sensor}}" }
   ]
  }
 ]
}