# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "root/volatile/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E488-FDB6";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "root/persistent/home";
      fsType = "zfs";
    };

  fileSystems."/mnt/nas" =
    { device = "data/nas";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "root/persistent/nix";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "root/persistent/persist";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
