{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"${host}-node\"} - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cpu) (node_cpu_seconds_total{job=\"${host}-node\"}))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"${host}-node\"}"
    }
   ]
  },
  {
   "title": "Load (1m avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"${host}-node\"}) / count(count by (cpu) (node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "Load (5m avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{job=\"${host}-node\"}) / count(count by (cpu) (node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "Load (15m avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{job=\"${host}-node\"}) / count(count by (cpu) (node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (cpu) (rate(node_cpu_seconds_total{mode!=\"idle\",job=\"${host}-node\"}[1m]))",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{job=\"${host}-node\"} / node_memory_MemTotal_bytes",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"${host}-node\"} / node_memory_MemTotal_bytes",
     "legendFormat": "Cached"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"${host}-node\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"${host}-node\"} / node_memory_MemTotal_bytes",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "container_start_time_seconds{job=\"${host}-cadvisor\",image!=\"\"} - scalar(node_boot_time_seconds{job=\"${host}-node\"})"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"e.*\",job=\"${host}-node\"}[1m])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"e.*\",job=\"${host}-node\"}[1m])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"${host}-node\",fstype!~\"(tmpfs|zfs)\",device!=\"none\"} - node_filesystem_avail_bytes",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "sum (label_replace(\nmax(node_filesystem_size_bytes{job=\"${host}-node\",fstype=\"zfs\",device=~\"[a-zA-Z].*/.*\"}) by (device)\n-\nmax(node_filesystem_avail_bytes{job=\"${host}-node\",fstype=\"zfs\",device=~\"[a-zA-Z].*/.*\"}) by (device)\n, \"pool\", \"$1\", \"device\", \"(.*?)/.*\")) by (pool)",
     "legendFormat": "\"{{pool}}\""
    }
   ]
  },
  {
   "title": "Speedtest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upload",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "scalar(speedtest_upload)" }
     ]
    },
    {
     "title": "Ping Latency",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "scalar(speedtest_ping_latency)" }
     ]
    },
    {
     "title": "Download",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "scalar(speedtest_download)" }
     ]
    }
   ]
  },
  {
   "title": "DNS Resolver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(dns_requests_total{job=\"${host}-resolved\"}[$__interval])",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Resolution",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "dns_resolver_authoritative_hit_total{job=\"${host}-resolved\"}",
       "legendFormat": "Authoritative"
      },
      {
       "expr": "dns_resolver_blocked_total{job=\"${host}-resolved\"}",
       "legendFormat": "Blocked"
      },
      {
       "expr": "dns_resolver_cache_hit_total{job=\"${host}-resolved\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "dns_resolver_override_hit_total{job=\"${host}-resolved\"}",
       "legendFormat": "Overridden"
      },
      {
       "expr": "dns_resolver_nameserver_hit_total{job=\"${host}-resolved\"} + dns_resolver_nameserver_miss_total{job=\"${host}-resolved\"}",
       "legendFormat": "Recursive"
      }
     ]
    },
    {
     "title": "Responses",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(dns_responses_total{job=\"${host}-resolved\"}[$__interval])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    }
   ]
  }
 ]
}