{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cpu) (node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Load (1m avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1) / count(count by (cpu) (node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "Load (5m avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5) / count(count by (cpu) (node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "Load (15m avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15) / count(count by (cpu) (node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"e.*\"}[1m])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"e.*\"}[1m])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "docker_container_running_state" },
    {
     "expr": "docker_container_start_time_seconds - scalar(node_boot_time_seconds)"
    },
    { "expr": "docker_container_restart_count" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) / count(count by (cpu) (node_cpu_seconds_total))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "Cached"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=\"/boot\"} / node_filesystem_size_bytes)",
     "legendFormat": "boot"
    },
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=\"/var/concourse-worker-scratch\"} / node_filesystem_size_bytes)",
     "legendFormat": "concourse"
    },
    {
     "expr": "sum(1 - (node_filesystem_avail_bytes{mountpoint=~\"(/|/home|/nix|/persist|/var/log)\"} / node_filesystem_size_bytes))",
     "legendFormat": "zfs"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=~\"(/|/boot|/home|/nix|/persist|/var/concourse-worker-scratch|/var/log)\"} - node_filesystem_avail_bytes",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Alert Rules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Boot Volume Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - node_filesystem_avail_bytes{mountpoint=\"/boot\"} / node_filesystem_size_bytes"
      }
     ]
    },
    {
     "title": "Concourse Volume Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - node_filesystem_avail_bytes{mountpoint=\"/var/concourse-worker-scratch\"} / node_filesystem_size_bytes"
      }
     ]
    },
    {
     "title": "ZFS Volume Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(1 - node_filesystem_avail_bytes{mountpoint=~\"(/|/home|/nix|/persist|/var/log)\"} / node_filesystem_size_bytes)"
      }
     ]
    },
    {
     "title": "BookDB Running Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(docker_container_running_state{name=~\"bookdb_(bookdb|db)_1\"})"
      }
     ]
    },
    {
     "title": "Bookmarks Running Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(docker_container_running_state{name=~\"bookmarks_(bookmarks|db)_1\"})"
      }
     ]
    },
    {
     "title": "Commento Running Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(docker_container_running_state{name=~\"commento_(server|db)_1\"})"
      }
     ]
    },
    {
     "title": "Concourse Running Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(docker_container_running_state{name=~\"concourse_(worker|web|db)_1\"})"
      }
     ]
    },
    {
     "title": "Etherpad Running Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(docker_container_running_state{name=~\"etherpad_(etherpad|db)_1\"})"
      }
     ]
    },
    {
     "title": "Gitea Running Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(docker_container_running_state{name=~\"gitea_(server|db)_1\"})"
      }
     ]
    },
    {
     "title": "Pleroma Running Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(docker_container_running_state{name=~\"pleroma_(pleroma|db)_1\"})"
      }
     ]
    },
    {
     "title": "Umami Running Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(docker_container_running_state{name=~\"umami_(server|db)_1\"})"
      }
     ]
    }
   ]
  }
 ]
}