{
 "title": "Concourse",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(concourse_builds_aborted_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Check Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "concourse_lidar_check_queue_size{job=\"$Job\"}",
     "legendFormat": "Check Queue Size"
    }
   ]
  },
  {
   "title": "Running Builds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "concourse_builds_running{job=\"$Job\"}",
     "legendFormat": "Running Builds"
    }
   ]
  },
  {
   "title": "Pipeline Build Durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(concourse_builds_duration_seconds_bucket{job=\"$Job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(concourse_http_responses_duration_seconds_bucket{job=\"$Job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "concourse_workers_registered{job=\"$Job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "concourse_workers_containers{job=\"$Job\"}",
     "legendFormat": "worker-{{worker}}"
    },
    {
     "expr": "concourse_workers_unknown_containers{job=\"$Job\"}",
     "legendFormat": "worker-{{worker}} (unknown)"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "concourse_workers_volumes{job=\"$Job\"}",
     "legendFormat": "worker-{{worker}}"
    },
    {
     "expr": "concourse_workers_unknown_volumes{job=\"$Job\"}",
     "legendFormat": "worker-{{worker}} (unknown)"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$Job\"}",
     "legendFormat": "{{quantile}}-quantile"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$Job\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{job=\"$Job\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$Job\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$Job\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$Job\"}[$__interval])",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}