name: Run tests

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Lint
        run: |
          set -ex
          nix flake check
          nix run .#fmt
          nix run .#lint
          git diff --exit-code
