name: Run tests

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        run: |
          nix-env --install nix-linter nixpkgs-fmt
      - name: Lint
        run: |
          set -ex
          find . -name '*.nix' -exec nixpkgs-fmt {} \;
          nix-lint -r .
          git diff --exit-code
