{
 "title": "lainon.life",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Listeners (channel)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (listeners) by (channel)", "legendFormat": "{{channel}}" }
   ]
  },
  {
   "title": "Listeners (format)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (listeners) by (format)", "legendFormat": "{{format}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (cpu)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "Cached"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"e.*\"}[1m])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"e.*\"}[1m])",
     "legendFormat": "Rx"
    }
   ]
  }
 ]
}